name: ash_trainer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  drift: ^2.24.2
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  drift_db_viewer: ^2.1.0
  health: ^13.0.0
  permission_handler: ^11.3.1
  uuid: ^4.5.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  flutter_displaymode: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.24.2
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
